name: Odoo Setup and Update

on:
  push:
    branches:
      - main  # Trigger the workflow when there is a push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow when there is a PR to the main branch 

jobs:
  setup:
    runs-on: self-hosted  # This will use your self-hosted runner
    
    steps:
      # Checkout the code from the repository (this will be done by your self-hosted runner)
      - name: Checkout code
        uses: actions/checkout@v2

      # Update apt and install dependencies
      - name: Update apt and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y python3-pip python3-dev libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libffi-dev libmysqlclient-dev libjpeg-dev libpq-dev libjpeg8-dev liblcms2-dev libblas-dev libatlas-base-dev npm postgresql git python3-venv

      # Set up Node.js and install necessary npm packages
      - name: Install Node.js and npm packages
        run: |
          if [ ! -e /usr/bin/node ]; then
            sudo ln -s /usr/bin/nodejs /usr/bin/node
          fi
          sudo npm install -g less less-plugin-clean-css
          sudo apt-get install -y node-less

      # Install missing dependencies for wkhtmltopdf
      - name: Install missing dependencies for wkhtmltopdf
        run: |
          sudo apt-get install -y fontconfig xfonts-base

      # Install wkhtmltopdf
      - name: Install wkhtmltopdf
        run: |
          sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
          sudo apt-get --fix-broken install -y

      # Create the Odoo user and set up the directory structure
      - name: Create Odoo user and set up directories
        run: |
          sudo adduser --system --home=/opt/odoo18 --group odoo18
          sudo su - postgres -c "createuser --createdb --username postgres --no-createrole --superuser --pwprompt odoo18"
          
          # Ensure the odoo18 user owns the directory and has the correct permissions
          sudo chown -R odoo18:odoo18 /opt/odoo18
          sudo chmod -R 755 /opt/odoo18

      # Set up Python virtual environment
      - name: Set up Python virtual environment
        run: |
          sudo python3 -m venv /opt/odoo18/venv
          cd /opt/odoo18/
          sudo chown -R odoo18:odoo18 /opt/odoo18/venv  # Ensure proper ownership
          source venv/bin/activate
          pip install -r requirements.txt
          deactivate

      # Copy Odoo config file and adjust settings
      - name: Copy and configure Odoo config
        run: |
          sudo cp /opt/odoo18/debian/odoo.conf /etc/odoo18.conf
          sudo sed -i 's/^; admin_passwd = admin$/admin_passwd = admin/' /etc/odoo18.conf
          sudo sed -i 's/^; db_password = False$/db_password = 123456/' /etc/odoo18.conf
          sudo sed -i 's/^addons_path = /opt\/odoo18\/addons/ &/' /etc/odoo18.conf

      # Set proper permissions for Odoo config
      - name: Set permissions for Odoo config file
        run: |
          sudo chown odoo18: /etc/odoo18.conf
          sudo chmod 640 /etc/odoo18.conf
          sudo mkdir /var/log/odoo
          sudo chown odoo18:root /var/log/odoo

      # Set up the Odoo service
      - name: Create and enable Odoo systemd service
        run: |
          sudo bash -c "cat <<EOF > /etc/systemd/system/odoo18.service
          [Unit]
          Description=Odoo18
          Documentation=http://www.odoo.com
          [Service]
          Type=simple
          User=odoo18
          ExecStart=/opt/odoo18/venv/bin/python3.12 /opt/odoo18/odoo-bin -c /etc/odoo18.conf
          [Install]
          WantedBy=default.target
          EOF"
          sudo chmod 755 /etc/systemd/system/odoo18.service
          sudo chown root: /etc/systemd/system/odoo18.service
          sudo systemctl daemon-reload
          sudo systemctl start odoo18.service
          sudo systemctl enable odoo18.service

      # Optionally, you can add a step to check if Odoo is running
      - name: Check Odoo service status
        run: |
          sudo systemctl status odoo18.service
